apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-app
  name: simple-app
  namespace: default
spec:
  ports:
  - nodePort: 31282
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: simple-app
  sessionAffinity: None
  type: NodePort
